In [29]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression as LR
from sklearn.model_selection import train_test_split

In [37]:
df = pd.read_excel('./data_source/test.xlsx')
df.rename(columns={'a':'x1','b':'x2'},inplace=True)
print(df.columns)
df

Index(['x1', 'x2', 'y'], dtype='object')


x1  x2   y
0   1   2   8
1   2   3  13
2   3   4  18
3   4   5  23
4   5   6  28
5   6   7  33
6   7   8  38
7   8   9  43

In [54]:
X = df[['x1','x2']]
y = df[['y']].values.tolist()

In [55]:
Xtrain, Xtest, Ytrain, Ytest = train_test_split(X,y,test_size=0.3,random_state=20)

In [56]:

reg = LR().fit(Xtrain,Ytrain)

In [57]:
score = reg.score(Xtrain,Ytrain)

In [58]:
score

1.0

In [59]:
Xtest

x1  x2
5   6   7
7   8   9
0   1   2

In [60]:
yhat =reg.predict(Xtest)
yhat

array([[33.],
       [43.],
       [ 8.]])

In [62]:
reg.coef_

array([[2.5, 2.5]])

In [47]:
[*zip(Xtrain.columns,reg.coef_[0])]

[('x1', 2.4999999999999996), ('x2', 2.500000000000001)]

In [23]:
from sklearn.linear_model import LinearRegression
 
X = [[1],[2],[3]]
y = [[6],[9],[14]]
 
model = LinearRegression(fit_intercept=True)
r = model.fit(X, y)
print (r)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)


In [24]:
x2 = [[4]]
y2 = model.predict(x2)


In [25]:
model.coef_

array([[4.]])

In [26]:
model.intercept_

array([1.66666667])

In [27]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import Pipeline

In [30]:
def polynomial_model(degree):
    polynomial_features = PolynomialFeatures(degree=degree,include_bias=False)
    linear_regression = LinearRegression(normalize=True)
    pipeline = Pipeline([("polynomial_features",polynomial_features),("linear_regression",linear_regression)])
    return pipeline

In [31]:
model = polynomial_model(2)
model.fit(X, y)

Pipeline(memory=None,
         steps=[('polynomial_features',
                 PolynomialFeatures(degree=2, include_bias=False,
                                    interaction_only=False, order='C')),
                ('linear_regression',
                 LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
                                  normalize=True))],
         verbose=False)

In [32]:
y2 = model.predict(x2)
y2

array([[21.]])

In [33]:
model.intercept_

AttributeError: 'Pipeline' object has no attribute 'intercept_'